vim.keymap.set('i', '<M-;>', 'æ', { desc = 'Insert æ' })
vim.keymap.set('i', '<S-M-;>', 'Æ', { desc = 'Insert Æ' })
vim.keymap.set('i', '<M-o>', 'ø', { desc = 'Insert ø' })
vim.keymap.set('i', '<S-M-o>', 'Ø', { desc = 'Insert Ø' })
vim.keymap.set('i', '<M-a>', 'å', { desc = 'Insert å' })
vim.keymap.set('i', '<S-M-a>', 'Å', { desc = 'Insert Å' })
